version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: node:16
    steps:
      - checkout
      - run: cp .env.sample .env
      - run: yarn
      - run: yarn build
      - run: scp -oStrictHostKeyChecking=no -r build/* gnosis@178.62.227.183:/var/www/html/
  deploy-surge:
    docker:
      - image: node:16
    steps:
      - checkout
      - run: cp .env.sample .env
      - run: yarn
      - run: yarn build      
      - run: npx surge --domain gb-faucet-ui-${CIRCLE_BRANCH}.surge.sh --project build 
                 
# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
      - deploy-surge:
          filters:
            branches:
              ignore:
                - master
                